{
  "regions": ["hnd1"],
  "functions": {
    "api/index.php": {
      "runtime": "vercel-php@0.4.0"
    }
  },
  "routes": [
    { "src": "/(.api/index.php)", "dest": "/$1" },
    { "handle": "filesystem" },
    { "src": "/.api/index.php", "dest": "/404.html" }
  ]
}