name: Chrome Extension Release

on:
  push:
    tags:
      - "cr*.*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Step0. Checkout repository
        uses: actions/checkout@v4
        
      # 拡張機能をzip化
      - name: Step1. 拡張機能をzip化する
        run: |
          echo "リポジトリを圧縮中..."
          zip -r sharetool-chrome.zip . -x "*.git*"

      - name: Step2. Chrome Web Store にアップロード＆公開！
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'publish'  # one of: upload, publish, testers
          client_id: ${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}
          extension_id: 'folhpgnfkkbpgchbambnjdkaaleaefgh' 
          zip_file: 'sharetool-chrome.zip'
