name: Chrome Extension Release

on:
  push:
    tags:
      - "cr*.*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Step0. Checkout repository
        uses: actions/checkout@v4
        
      # 拡張機能をzip化
      - name: Step1. 拡張機能をzip化する
        run: |
          echo "リポジトリを圧縮中..."
          zip -r sharetool-chrome.zip . -x "*.git*"

      - name: Step2. Chrome Web Store にアップロード＆公開！
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: sharetool-chrome.zip
          extension-id: folhpgnfkkbpgchbambnjdkaaleaefgh
          client-id: ${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}
