name: Chrome Extension Release

on:
  release:
    types:
      - published  # リリースが公開されたときにトリガー

jobs:
  release:
    if: github.ref_name == 'chrome'  # chromeブランチ限定
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # manifest.jsonのversionを更新
      - name: Update version in manifest.json
        id: update_manifest
        run: |
          RELEASE_NAME="${{ github.event.release.tag_name }}"
          VERSION=$(echo "$RELEASE_NAME" | sed -E 's/^cr//')
          jq --arg version "$VERSION" '.version = $version' manifest.json > manifest_updated.json
          mv manifest_updated.json manifest.json

      # manifest.jsonの更新をコミット
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add manifest.json
          git commit -m "Update manifest.json version to $VERSION"

      # 拡張機能をzip化
      - name: Create zip package
        run: |
          zip -r chrome_extension.zip . -x "*.git*"

      # Chrome Web Store にアップロード
      - name: Upload to Chrome Web Store
        uses: chrome-webstore/upload-cli@v1
        with:
          client_id: ${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          source: ./chrome_extension.zip

      # 公開をトリガー
      - name: Publish extension
        uses: chrome-webstore/publish-cli@v1
        with:
          client_id: ${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
